---
title: "Data Manipulation"
author: "Shuo Yan"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


## Import FAS csv files

 Impprt my csv files to use as examples.
 
```{r}
litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```


## Select variables
... by listing
```{r}
select(
  litters_data, group, litter_number, gd0_weight)

select(
  litters_data, litter_number, gd0_weight, pups_survive
)

```

...by specifying a range:

```{r}
select(litters_data, gd_of_birth:pups_survive)

select(litters_data, group, gd_of_birth:pups_survive)

```


... by saying what you wat to remove:

```{r}
select(litters_data, -litter_number)
```
... and rename

```{r}
select(litters_data, group, litter_number, gest_day_0_weight = gd0_weight)
rename(litters_data, gest_day_0_weight = gd0_weight)
```
... use select helpers:
```{r}
select(litters_data, starts_with("gd"))

select(litters_data, litter_number, starts_with("pup"))

select(litters_data, litter_number, everything())

```
## Filter observations

Do some filtering!

```{r}
filter(litters_data, gd0_weight < 25)

filter(litters_data, gd0_weight >= 25)

filter(litters_data, pups_born_alive == 8)

filter(litters_data, !is.na(gd0_weight))

filter(litters_data, group == "Low8" | group == "Low7")
filter(litters_data, group %in% c("Low7", "Low8"))

filter(litters_data, pups_born_alive %in% 4:6)

filter(litters_data, pups_born_alive %in% 4:7, !is.na(gd0_weight))

```










