---
title: "Data Import"
author: "Shuo Yan"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


## Import FAS csv files

 Impprt my first csv (`FAS_litters.csv`).
 
```{r}
 litters_data = read_csv(file = "./data/FAS_litters.csv")
 litters_data = janitor::clean_names(litters_data)
```

Import the pups data also.

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")
```


## Look at data

 Look at litters data
 
 ```{r}
 head(litters_data)
 tail(litters_data)
 
 skimr::skim(litters_data)

 ```
 Skip some rows; omit variable names.
 
```{r}
 litters_data = read_csv(file = "./data/FAS_litters.csv",
  skip = 10, col_names = FALSE)
```
 
 Take a look at pups!

```{r}
pups_data = read_csv("./data/FAS_pups.csv", col_types = "ciiiii")
pups_data = jonitor::clean_names(pups_data)
skimr::skim(pups_data)
```


## Other formats

Read in mlb data

```{r}
mlb_data = readxl::read_excel(path = "./data/mlb11.xlsx")

mlb_subset = readxl::read_excel(path = "./data/mlb11.xlsx", range = "A1:E17")

```
Read in pulse data
```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")
```

## Compars with base R

```{r}
pups_readr = read_csv("./data/FAS_pups.csv")
pups_baser = read.csv("./data/FAS_pups.csv")

```