---
title: "Tidy data"
author: "Shuo Yan"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


## gather
 PULSE data
 
```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
pulse_data
```
This isn't tidy yet ...

```{r}
pulse_tidy = pulse_data %>%
  gather(key = "visit", value = "bdi_score", bdi_score_bl:bdi_score_12m)
```

Illustrate `separate`

```{r}
pulse_tidy %>%
  separate(visit, into = c("bdi_str", "score_str", "visit"), sep = "_") %>%
select(-bdi_str, -score_str) %>%
mutate(visit = replace(visit, visit == "bl", "00m"))
```
All together, the data import / cleaning pipeline is:

```{r}
pulse_df =
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
   gather(key = "visit", value = "bdi_score", bdi_score_bl:bdi_score_12m) %>%
   separate(visit, into = c("bdi_str", "score_str", "visit"), sep = "_") %>%
select(-bdi_str, -score_str) %>%
mutate(visit = replace(visit, visit == "bl", "00m"))
```

## Revisit FAS_litters

```{r}
litters_data = read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day"), 3)
```
Data cleaning / tidying:

```{r}
litters_data = read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(litter_number, ends_with("weight")) %>%
  gather(key = "gest_day", value = "weight", gd0_weight:gd18_weight) %>%
mutate(gest_day = recode(gest_day, "gd0_weight" = 0, "gd18_weight" = 18)) %>%
    arrange(litter_number)

```
## Spread

```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)

```
Make it readable:

```{r}
analysis_result %>%
  spread(key = time, value = mean) %>%
  knitr::kable()
```
## Bind rows

Read in LotR data:

```{r}
fellowship_ring = readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")
```
Creat final LotR data:

```{r}
bind_rows(fellowship_ring, two_towers, return_king) %>%
  janitor::clean_names() %>%
  gather(key = sex, value = word, female:male) %>%
  mutate(race = tolower(race))
```

## Join data

Load the FAS datasets

```{r}

pup_data = read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = tolower(group))

```

Creat joined data:

```{r}
fas_data = left_join(pup_data, litter_data, by = "litter_number")
```

